version: '2'

services:
    microk8s-discord-bot:
        image: 192.168.1.151:32000/microk8s-discord-bot:1.0.143
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
          - "5001:443"